# Generated by Django 5.0.7 on 2024-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_travel_comfort_rating_remove_travel_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='title',
        ),
        migrations.AddField(
            model_name='travel',
            name='convenience_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='cultural_heritage_sites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='places_to_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='population_density_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='safety_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='vegetation_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
